#!/usr/bin/env php
<?php
/**
 * @file
 * dpkg-scanpackages
 * build.php
 *
 * Created by Jake Wise 06/01/2017.
 *
 * You are permitted to use, modify, and distribute this file in accordance with
 * the terms of the license agreement accompanying it.
 */

if (!file_exists('composer.phar')) {
    copy('https://getcomposer.org/installer', 'composer-setup.php');

    if (hash_file('SHA384', 'composer-setup.php') === '55d6ead61b29c7bdee5cccfb50076874187bd9f21f65d8991d46ec5cc90518f447387fb9f76ebae1fbbacf329e583e30') {
        echo 'Installer verified' . PHP_EOL;
        system('php composer-setup.php');
    } else {
        echo 'Installer corrupt' . PHP_EOL;
    }

    unlink('composer-setup.php');
}

system('cd app && ../composer.phar install');

print 'Building dpkg-scanpackages.phar' . PHP_EOL;

$phar = new Phar('dpkg-scanpackages.phar');
$phar->startBuffering();
$phar->buildFromDirectory('app');
$phar->setSignatureAlgorithm(Phar::SHA256);
$phar->setStub('#!/usr/bin/env php' . PHP_EOL . $phar->createDefaultStub('bin/dpkg-scanpackages'));
$phar->compressFiles(Phar::GZ);
$phar->stopBuffering();

print 'Done' . PHP_EOL;
