#!/usr/bin/env php
<?php
/**
 * @file
 * dpkg-scanpackages
 * build.php
 *
 * Created by Jake Wise 06/01/2017.
 *
 * You are permitted to use, modify, and distribute this file in accordance with
 * the terms of the license agreement accompanying it.
 */

system('cd app && composer.phar install');

print 'Building dpkg-scanpackages.phar' . PHP_EOL;

$phar = new Phar('dpkg-scanpackages.phar');
$phar->startBuffering();
$phar->buildFromDirectory('app');
$phar->setSignatureAlgorithm(Phar::SHA256);
$phar->setStub('#!/usr/bin/env php' . PHP_EOL . $phar->createDefaultStub('bin/dpkg-scanpackages'));
$phar->compressFiles(Phar::GZ);
$phar->stopBuffering();

print 'Done' . PHP_EOL;
